export default {
  INITIALISE_STORE: 'INITIALISE_STORE',

  ACTIVATE_DRAWER: 'ACTIVATE_DRAWER',
  DEACTIVATE_DRAWER: 'DEACTIVATE_DRAWER',

  SET_SPINNER_STATE: 'SET_SPINNER_STATE',

  UNLOCK_WALLET: 'UNLOCK_WALLET',
  SET_WALLET_ADDRESS: 'SET_WALLET_ADDRESS',
  SET_WALLET_BALANCE: 'SET_WALLET_BALANCE',
  SET_ACTIVE_TOKEN: 'SET_ACTIVE_TOKEN',

  SET_TOKENS: 'SET_TOKENS',

  SET_LOGS: 'SET_LOGS',
  ADD_LOCAL_LOG: 'ADD_LOCAL_LOG',

  SET_NETWORK: 'SET_NETWORK',

  SET_TX_OBJECT: 'SET_TX_OBJECT',
  CLEAR_TX: 'CLEAR_TX',

  SET_OVERLAY_COLOR: 'SET_OVERLAY_COLOR',
  UNSET_OVERLAY_COLOR: 'UNSET_OVERLAY_COLOR',

  SHOW_DIALOG: 'SHOW_DIALOG',
  CLEAR_DIALOG: 'CLEAR_DIALOG',

  SET_DAPP_WHITELIST: 'SET_DAPP_WHITELIST',
  SET_DAPP_WHITELIST_TIMER: 'SET_DAPP_WHITELIST_TIMER',
  ADD_CONTRACT_TO_DAPP_WHITELIST: 'ADD_CONTRACT_TO_DAPP_WHITELIST',
  REMOVE_DAPP_FROM_WHITELIST: 'REMOVE_DAPP_FROM_WHITELIST',
}
