export const INITIALISE_STORE = 'INITIALISE_STORE'

export const ACTIVATE_DRAWER = 'ACTIVATE_DRAWER'
export const DEACTIVATE_DRAWER = 'DEACTIVATE_DRAWER'

export const SET_SPINNER_STATE = 'SET_SPINNER_STATE'

export const SET_WALLET_ADDRESS = 'SET_WALLET_ADDRESS'
export const SET_WALLET_BALANCE = 'SET_WALLET_BALANCE'
export const SET_ACTIVE_TOKEN = 'SET_ACTIVE_TOKEN'

export const SET_TOKENS = 'SET_TOKENS'

export const SET_LOGS = 'SET_LOGS'
export const ADD_LOCAL_LOG = 'ADD_LOCAL_LOG'

export const SET_NETWORK = 'SET_NETWORK'

export const SET_TX_OBJECT = 'SET_TX_OBJECT'
export const CLEAR_TX = 'CLEAR_TX'

export const SET_DAPP_WHITELIST = 'SET_DAPP_WHITELIST'
export const SET_DAPP_WHITELIST_TIMER = 'SET_DAPP_WHITELIST_TIMER'
export const ADD_CONTRACT_TO_DAPP_WHITELIST = 'ADD_CONTRACT_TO_DAPP_WHITELIST'
export const REMOVE_DAPP_FROM_WHITELIST = 'REMOVE_DAPP_FROM_WHITELIST'
