export default {
  INITIALISE_STORE: 'INITIALISE_STORE',
  INITIALISE_REMOTE_STORE: 'INITIALISE_REMOTE_STORE',
  MERGE_REMOTE_STORE: 'MERGE_REMOTE_STORE',
  STORE_LOADED: 'STORE_LOADED',

  ACTIVATE_DRAWER: 'ACTIVATE_DRAWER',
  DEACTIVATE_DRAWER: 'DEACTIVATE_DRAWER',

  SET_SPINNER_STATE: 'SET_SPINNER_STATE',

  UNLOCK_WALLET: 'UNLOCK_WALLET',
  SET_WALLET_ADDRESS: 'SET_WALLET_ADDRESS',
  SET_WALLET_BALANCE: 'SET_WALLET_BALANCE',
  SET_WALLET_STAKED: 'SET_WALLET_STAKED',
  SET_ACTIVE_TOKEN: 'SET_ACTIVE_TOKEN',

  DELETE_WALLET: 'DELETE_WALLET',
  CLEAR_STATE_FOR_HD_WALLET: 'CLEAR_STATE_FOR_HD_WALLET',

  SET_TOKENS: 'SET_TOKENS',

  PUSH_LOGS: 'PUSH_LOGS',
  ADD_LOCAL_LOG: 'ADD_LOCAL_LOG',
  RESET_LOGS: 'RESET_LOGS',

  SET_NETWORK: 'SET_NETWORK',
  SET_NETWORK_CHAIN_ID: 'SET_NETWORK_CHAIN_ID',
  SET_NETWORK_STATUS: 'SET_NETWORK_STATUS',
  SET_LEDGER_SUPPORTED_CONNECTION_TYPES:
    'SET_LEDGER_SUPPORTED_CONNECTION_TYPES',
  SET_LEDGER_TRANSPORT_GETTER_INTERNAL_MUTATE:
    'SET_LEDGER_TRANSPORT_GETTER_INTERNAL_MUTATE',
  SET_LEDGER_TRANSPORT_GETTER: 'SET_LEDGER_TRANSPORT_GETTER',

  SET_TX_OBJECT: 'SET_TX_OBJECT',
  SET_TX_JOB_ID: 'SET_TX_JOB_ID',
  CLEAR_TX: 'CLEAR_TX',
  SET_AMOUNT_OF_WORK: 'SET_AMOUNT_OF_WORK',
  SET_SINGLE_TX_AMOUNT_OF_WORK: 'SET_SINGLE_TX_AMOUNT_OF_WORK',

  SET_OVERLAY_COLOR: 'SET_OVERLAY_COLOR',
  UNSET_OVERLAY_COLOR: 'UNSET_OVERLAY_COLOR',

  SHOW_DIALOG: 'SHOW_DIALOG',
  CLEAR_DIALOG: 'CLEAR_DIALOG',

  SET_DAPP_WHITELIST: 'SET_DAPP_WHITELIST',
  SET_DAPP_WHITELIST_TIMER: 'SET_DAPP_WHITELIST_TIMER',
  ADD_CONTRACT_TO_DAPP_WHITELIST: 'ADD_CONTRACT_TO_DAPP_WHITELIST',
  REMOVE_DAPP_FROM_WHITELIST: 'REMOVE_DAPP_FROM_WHITELIST',

  GRANT_SAFARI_ACCESS: 'GRANT_SAFARI_ACCESS',
}
